### ISSUE TITLE
Unable to successfully run stryker using the given instructions (react)

### ISSUE THREAD

**Issue by variousauthors** [Archcry/stryker-webpack-docs#1]
Hello, I see that you've updated these docs recently. Nevertheless, it seems that I am unable to start a new project with the instructions given.

(you can play with stryker-test-5 [on github][0] if you like, thank you for your hard work!)

```
✔ ~/Github/Personal/ReactJS 
20:49 $ cd stryker-test-2/
✔ ~/Github/Personal/ReactJS/stryker-test-2 
20:49 $ node --version
v8.9.1
✔ ~/Github/Personal/ReactJS/stryker-test-2 
20:49 $ npm --version
5.6.0
```

I am using nvm to manage node versions, so I installed stryker locally rather than globally.

```
✔ ~/Github/Personal/ReactJS/stryker-test-2 
20:49 $  npm install --save-dev stryker stryker-api
+ stryker-api@0.12.0
+ stryker@0.18.0
added 23 packages in 7.812s
```

Because stryker is installed locally, I run the `stryker init` command from `node_modules/.bin`. I chose the options specified in the readme. (notably, the optional "what kind of transformations should be applied to your code?" prompt includes 2 options labelled `webpack`, but I choose neither of them in keeping with your instructions).

```
✔ ~/Github/Personal/ReactJS/stryker-test-2 
20:51 $ node_modules/.bin/stryker init
? Which test runner do you want to use? jest
No stryker test framework plugin found that is compatible with jest, downgrading coverageAnalysis to "all"
? What kind of code do you want to mutate? javascript
? [optional] What kind transformations should be applied to your code? 
? Which reporter(s) do you want to use? clear-text, progress
Installing NPM dependencies...
npm i --save-dev stryker-api stryker-jest-runner stryker-javascript-mutator
npm WARN stryker-jest-runner@0.3.0 requires a peer of jest-cli@>=18.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stryker-jest-runner@0.3.0 requires a peer of stryker-api@^0.10.0 but none is installed. You must install peer dependencies yourself.

+ stryker-jest-runner@0.3.0
+ stryker-api@0.12.0
+ stryker-javascript-mutator@0.3.2
added 3 packages and updated 1 package in 6.206s
Writing stryker.conf.js...
Done configuring stryker. Please review `stryker.conf.js`, you might need to configure your files and test runner correctly.
Let's kill some mutants with this command: `stryker run`
```

Eager to kill some mutants, I update my `package.json` and `stryker.conf.js` files to reflect your instructions.

```
✔ ~/Github/Personal/ReactJS/stryker-test-2 
20:54 $ cat stryker.conf.js 
module.exports = function(config) {
  config.set({
    files: [
      { pattern: "src/**/*.js", mutated: true, included: false },
      "!src/**/*.test.js",
      "src/**/**/*",
    ],
    testRunner: "jest",
    mutator: "javascript",
    transpilers: [],
    reporter: ["clear-text", "progress"],
    coverageAnalysis: "off",
        jest: {
      project: 'react'
    }
  });
};
✔ ~/Github/Personal/ReactJS/stryker-test-2 
20:54 $ cat package.json 
{
  "name": "stryker-test-2",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "react-scripts": "1.1.0",
    "stryker": "^0.18.0",
    "stryker-api": "^0.12.0",
    "stryker-javascript-mutator": "^0.3.2",
    "stryker-jest-runner": "^0.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "stryker": "stryker run",
    "eject": "react-scripts eject"
  }
}
```

Hungrily, I run the command.

```
✔ ~/Github/Personal/ReactJS/stryker-test-2 
20:54 $ npm run stryker

> stryker-test-2@0.1.0 stryker /Volumes/Github/Personal/ReactJS/stryker-test-2
> stryker run

[2018-01-16 20:55:19.191] [INFO] ConfigReader - Using stryker.conf.js in the current working directory.
[2018-01-16 20:55:19.234] [WARN] PluginLoader - Error during loading "stryker-jest-runner" plugin:
  Cannot find module 'jest-cli/package.json'
[2018-01-16 20:55:19.249] [INFO] InputFileResolver - Found 3 of 7 file(s) to be mutated.
[2018-01-16 20:55:19.250] [INFO] InitialTestExecutor - Starting initial test run. This may take a while.
[2018-01-16 20:55:19.585] [ERROR] TestRunnerChildProcessAdapter - /Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/stryker-api/src/core/Factory.js:43
            throw new Error("Could not find a " + this.factoryName + " with name " + name + ", did you install it correctly (for example: npm install --save-dev " + this.importSuggestion(name) + ")?");
            ^

Error: Could not find a testrunner with name jest, did you install it correctly (for example: npm install --save-dev stryker-jest-runner)?
    at TestRunnerFactory.Factory.create (/Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/stryker-api/src/core/Factory.js:43:19)
    at IsolatedTestRunnerAdapterWorker.start (/Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/stryker/src/isolated-runner/IsolatedTestRunnerAdapterWorker.js:60:80)
    at process.<anonymous> (/Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/stryker/src/isolated-runner/IsolatedTestRunnerAdapterWorker.js:20:27)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

[2018-01-16 20:55:19.591] [ERROR] TestRunnerChildProcessAdapter - Child process exited with non-zero exit code 1. Last 10 message from the child process were: 
	[2018-01-16 20:55:19.378] [DEBUG] PluginLoader - Loading stryker-* from /Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules

	[2018-01-16 20:55:19.381] [DEBUG] PluginLoader - Loading plugins stryker-javascript-mutator (matched with expression stryker-*)

	[2018-01-16 20:55:19.381] [DEBUG] PluginLoader - Loading plugins stryker-jest-runner (matched with expression stryker-*)

	[2018-01-16 20:55:19.381] [DEBUG] PluginLoader - Loading plugins stryker-javascript-mutator

	[2018-01-16 20:55:19.583] [DEBUG] PluginLoader - Loading plugins stryker-jest-runner

	[2018-01-16 20:55:19.584] [WARN] PluginLoader - Error during loading "stryker-jest-runner" plugin:
  Cannot find module 'jest-cli/package.json'

	[2018-01-16 20:55:19.584] [DEBUG] IsolatedTestRunnerAdapterWorker - Changing current working directory for this process to /Volumes/Github/Personal/ReactJS/stryker-test-2/.stryker-tmp/sandbox4825552

[2018-01-16 20:55:19.591] [ERROR] StrykerCli - an error occurred Test runner child process exited with non-zero exit code 1
```

I am most interested in the following line:

```
[2018-01-16 20:55:19.584] [WARN] PluginLoader - Error during loading "stryker-jest-runner" plugin:
  Cannot find module 'jest-cli/package.json'
```

I had already installed `stryker-jest-runner`, but a peer dependency was unmet.

```
✔ ~/Github/Personal/ReactJS/stryker-test-2 
20:55 $ npm i
npm WARN stryker-jest-runner@0.3.0 requires a peer of jest-cli@>=18.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stryker-jest-runner@0.3.0 requires a peer of stryker-api@^0.10.0 but none is installed. You must install peer dependencies yourself.

up to date in 4.765s
✔ ~/Github/Personal/ReactJS/stryker-test-2 
20:55 $ npm i --save-dev jest-cli
npm WARN stryker-jest-runner@0.3.0 requires a peer of stryker-api@^0.10.0 but none is installed. You must install peer dependencies yourself.

+ jest-cli@22.1.1
added 129 packages in 9.079s
✔ ~/Github/Personal/ReactJS/stryker-test-2 
```

With peer dependencies met, I run the command again.

```
20:56 $ npm run stryker

> stryker-test-2@0.1.0 stryker /Volumes/Github/Personal/ReactJS/stryker-test-2
> stryker run

[2018-01-16 20:56:31.932] [INFO] ConfigReader - Using stryker.conf.js in the current working directory.
[2018-01-16 20:56:32.050] [INFO] InputFileResolver - Found 3 of 7 file(s) to be mutated.
[2018-01-16 20:56:32.051] [INFO] InitialTestExecutor - Starting initial test run. This may take a while.
[2018-01-16 20:56:33.109] [ERROR] InitialTestExecutor - One or more tests resulted in an error:
	SyntaxError: Unexpected token import
[2018-01-16 20:56:33.109] [ERROR] StrykerCli - an error occurred Error: Something went wrong in the initial test run
    at InitialTestExecutor.validateResult (/Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/stryker/src/process/InitialTestExecutor.js:94:15)
    at InitialTestExecutor.<anonymous> (/Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/stryker/src/process/InitialTestExecutor.js:33:30)
    at step (/Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/tslib/tslib.js:131:27)
    at Object.next (/Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/tslib/tslib.js:112:57)
    at fulfilled (/Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/tslib/tslib.js:102:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I can see what is wrong: `import` is not part of ES5, it is part of ES6. Support for the keyword `import` is part of the reason I want to use webpack in the first place. I decide to add `webpack` as a `transpiler` to the `stryker.conf.js` file, since this is what `stryker init` does when the `webpack` option is checked.

Then I run stryker once, install `stryker-webpack` and then run stryker again.

```
✔ ~/Github/Personal/ReactJS/stryker-test-2 
21:10 $ npm run stryker

> stryker-test-2@0.1.0 stryker /Volumes/Github/Personal/ReactJS/stryker-test-2
> stryker run

[2018-01-16 21:10:05.631] [INFO] ConfigReader - Using stryker.conf.js in the current working directory.
[2018-01-16 21:10:05.909] [INFO] InputFileResolver - Found 3 of 7 file(s) to be mutated.
[2018-01-16 21:10:05.910] [INFO] InitialTestExecutor - Starting initial test run. This may take a while.
[2018-01-16 21:10:06.000] [ERROR] StrykerCli - an error occurred Error: Could not transpile input files: Execute webpack: Error: 
ERROR in multi ./src/main.js
Module not found: Error: Can't resolve '/Volumes/Github/Personal/ReactJS/stryker-test-2/src/main.js' in '/Volumes/Github/Personal/ReactJS/stryker-test-2'
 @ multi ./src/main.js
    at InitialTestExecutor.<anonymous> (/Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/stryker/src/process/InitialTestExecutor.js:54:31)
    at step (/Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/tslib/tslib.js:131:27)
    at Object.next (/Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/tslib/tslib.js:112:57)
    at fulfilled (/Volumes/Github/Personal/ReactJS/stryker-test-2/node_modules/tslib/tslib.js:102:62)
    at <anonymous>
```

Here the error is different. Unsure how to proceed, I create the file `./src/main.js` and run stryker again.

```
✔ ~/Github/Personal/ReactJS/stryker-test-2 
21:30 $ npm run stryker

> stryker-test-2@0.1.0 stryker /Volumes/Github/Personal/ReactJS/stryker-test-2
> stryker run

[2018-01-16 21:30:48.896] [INFO] ConfigReader - Using stryker.conf.js in the current working directory.
[2018-01-16 21:30:49.164] [INFO] InputFileResolver - Found 4 of 8 file(s) to be mutated.
[2018-01-16 21:30:49.166] [INFO] InitialTestExecutor - Starting initial test run. This may take a while.
[2018-01-16 21:30:49.867] [WARN] InitialTestExecutor - No tests were executed. Stryker will exit prematurely. Please check your configuration.
[2018-01-16 21:30:49.941] [INFO] Stryker - 53 Mutant(s) generated
```

Success! Though, not completely. The report claims that no tests were executed. This is strange, since the basic `create-react-app` (I am using v1.3.0) includes the test file `App.test.js` by default. Curious, I run `npm test`. The only output is:

```
Determining test suites to run...
--watch is not supported without git/hg, please use --watchAll 
npm ERR! Test failed.  See above for more details.
```

In order to validate this result, I create a new react-app and run the tests without stryker. The tests pass. I am determined to see this through. Running the command `node_modules/.bin/jest --env=jsdom` I get the following:

```
✘-1 ~/Github/Personal/ReactJS/stryker-test-2 
21:37 $ node_modules/.bin/jest --env=jsdom
 FAIL  .stryker-tmp/sandbox4825552/src/App.test.js
  ● Test suite failed to run

    TypeError: environment.setup is not a function
      
      at node_modules/jest-runner/build/run_test.js:112:23

 FAIL  .stryker-tmp/sandbox8650214/src/App.test.js
  ● Test suite failed to run

    TypeError: environment.setup is not a function
      
      at node_modules/jest-runner/build/run_test.js:112:23

 FAIL  src/App.test.js
  ● Test suite failed to run

    TypeError: environment.setup is not a function
      
      at node_modules/jest-runner/build/run_test.js:112:23

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        0.624s
Ran all test suites.
```

It appears that jest is finding the sandbox files created by stryker, which I guess is to be expected given how jest finds test files.

Determined to kill mutants, I repeat the above steps in a new app using `create-react-app@v1.5` running `npm test` after each step, in order to find out just when exactly `npm test` stops working (and why).

After installing `jest-cli` the command `npm test` fails to run tests. Without installing `jest-cli`, stryker fails to run. The error message when I run `npm test` is:

```
--watch is not supported without git/hg, please use --watchAll 
```

Based on this feedback I run `git init` and rerun `npm test`. Now the output is:

```
 FAIL  src/App.test.js
  ● Test suite failed to run

    TypeError: environment.setup is not a function
      
      at node_modules/jest-runner/build/run_test.js:112:23

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.394s
Ran all test suites related to changed files.
```

This is similar to the output shown above when running `node_modules/.bin/jest --env=jsdom`.

I set `jest-cli` to version `18.0.0` since this is closer to the version specified by the `stryker-jest-runner` peer dependencies. The command `npm test` now fails with 

```
TypeError: Path must be a string. Received [ '/Volumes/Github/Personal/ReactJS/stryker-test-5' ]
```

Where as `npm run stryker` outputs the following, and then hangs.

```
[2018-01-16 22:15:21.184] [INFO] ConfigReader - Using stryker.conf.js in the current working directory.
[2018-01-16 22:15:21.186] [DEBUG] PluginLoader - Loading stryker-* from /Volumes/Github/Personal/ReactJS/stryker-test-5/node_modules
[2018-01-16 22:15:21.187] [DEBUG] PluginLoader - Loading plugins stryker-javascript-mutator (matched with expression stryker-*)
[2018-01-16 22:15:21.187] [DEBUG] PluginLoader - Loading plugins stryker-jest-runner (matched with expression stryker-*)
[2018-01-16 22:15:21.187] [DEBUG] PluginLoader - Loading plugins stryker-webpack (matched with expression stryker-*)
[2018-01-16 22:15:21.187] [DEBUG] PluginLoader - Loading plugins stryker-javascript-mutator
[2018-01-16 22:15:21.216] [DEBUG] PluginLoader - Loading plugins stryker-jest-runner
[2018-01-16 22:15:21.277] [DEBUG] PluginLoader - Loading plugins stryker-webpack
[2018-01-16 22:15:21.427] [DEBUG] Stryker - Using config: {"logLevel":"debug","timeoutMs":5000,"timeoutFactor":1.5,"plugins":["stryker-*"],"port":9234,"reporter":["clear-text","progress"],"coverageAnalysis":"off","mutator":"javascript","transpilers":["webpack"],"maxConcurrentTestRunners":null,"thresholds":{"high":80,"low":60,"break":null},"files":[{"pattern":"src/**/*.js","mutated":true,"included":false},"!src/**/*.test.js","src/**/**/*"],"testRunner":"jest","jest":{"project":"react"},"configFile":"stryker.conf.js"}
[2018-01-16 22:15:21.427] [DEBUG] TestFrameworkOrchestrator - The `coverageAnalysis` setting is "off", not hooking into the test framework to achieve performance benefits.
[2018-01-16 22:15:21.440] [INFO] InputFileResolver - Found 4 of 8 file(s) to be mutated.
[2018-01-16 22:15:21.440] [DEBUG] InputFileResolver - All input files in order:
	/Volumes/Github/Personal/ReactJS/stryker-test-5/src/App.js (included: false, mutated: true),
	/Volumes/Github/Personal/ReactJS/stryker-test-5/src/index.js (included: false, mutated: true),
	/Volumes/Github/Personal/ReactJS/stryker-test-5/src/main.js (included: false, mutated: true),
	/Volumes/Github/Personal/ReactJS/stryker-test-5/src/registerServiceWorker.js (included: false, mutated: true),
	/Volumes/Github/Personal/ReactJS/stryker-test-5/src/App.css (included: true, mutated: false),
	/Volumes/Github/Personal/ReactJS/stryker-test-5/src/App.test.js (included: true, mutated: false),
	/Volumes/Github/Personal/ReactJS/stryker-test-5/src/index.css (included: true, mutated: false),
	/Volumes/Github/Personal/ReactJS/stryker-test-5/src/logo.svg (included: true, mutated: false)
[2018-01-16 22:15:21.441] [INFO] InitialTestExecutor - Starting initial test run. This may take a while.
[2018-01-16 22:15:21.542] [DEBUG] InitialTestExecutor - Transpiled files in order:
bundle.js (included: false)
[2018-01-16 22:15:21.542] [DEBUG] Sandbox - Creating a sandbox for files in /Volumes/Github/Personal/ReactJS/stryker-test-5/.stryker-tmp/sandbox5671879
[2018-01-16 22:15:21.544] [DEBUG] Sandbox - Creating test runner 0 using settings {port: 9234}
```

At this point I am ready for bed, so I create [a git repo][0] and include the link in this issue. Thank you for taking the time to read this! Once I am able to install and run stryker in a create-react-app app I will be sure to use what I know to clarify and update your README, if you like.

[0]: https://github.com/variousauthors/stryker-test-5

**Comment by Archcry** [comment]
Awesome that you're using Stryker on your React project, the problem currently lies in the fact that the new Jest runner is not released yet. The instructions are made to work with the new Jest runner but at this moment it's still pending as a pull-request: https://github.com/stryker-mutator/stryker-jest-runner/pull/25

What you can do however is clone the jest runner repository, build the feat-new-jest-runner branch and install it into your react project with `install-local` (https://www.npmjs.com/package/install-local). It's not the ideal solution but it's currently the only solution untill the new sryker-jest-runner is released.

I would love to hear your feedback :D

**Comment by variousauthors** [comment]
I'll let you know how things go ;) mutation-testing really feels like a really worthwhile tool!

**Comment by Archcry** [comment]
Awesome, let me know if it worked for you :D

**Comment by variousauthors** [comment]
I just had a baby and haven't been able to get back to this yet, but it looks like the jest-runner PR was merged?

**Comment by variousauthors** [comment]
Definitely just got it running with no webpack and no typescript (just a basic create-react-app project). It took a bit of tinkering, I'll let you know the full set of steps I took once I can get it working with webpack and typescript.

Bedankt!

**Comment by Archcry** [comment]
Awesome!

**Comment by variousauthors** [comment]
Sorry to leave you hanging for so long! January 18th I had a son, and haven't had as much time for tinkering since! I hope to get back to this, but feel free to close if you want to reduce clutter!

**Comment by Archcry** [comment]
The Webpack plugin has evolved a lot since this pull-request was started. I suggest you simply try again and report issues in the official Stryker repository since the Webpack plugin is officially adopted there now. Closing this issue now.
